#cloud-config

users:
  - name: terraform
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    plain_text_passwd: "Terraform123!"
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_key}

package_update: true
package_upgrade: true
packages:
  - wget
  - ntpdate